In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [2]:
folder = "~/Desktop/Design Teams/QMIND"
file = "LargerSet_4T.csv"

df = pd.read_csv(os.path.join(folder, file))

In [3]:
df = df.rename(columns={'Unnamed: 0': 'Seq'})
# df = df.drop(columns=['Unnamed: 0.1'])
df = df.set_index('Seq')
df.head(10)

OdomPosX   OdomPosY  OdomOrientZ  OdomOrientW  OdomLinX  OdomAngZ  \
Seq                                                                      
0   -4.032375  18.373403     0.093063     0.995660  0.152541  0.000100   
1   -4.031664  18.373537     0.093066     0.995660  0.153398  0.000885   
2   -4.029840  18.373881     0.093065     0.995660  0.151111  0.000587   
3   -4.028017  18.374225     0.093065     0.995660  0.148823  0.000288   
4   -4.026193  18.374569     0.093065     0.995660  0.146536 -0.000010   
5   -4.025571  18.374686     0.093069     0.995660  0.146829  0.000229   
6   -4.024949  18.374804     0.093073     0.995659  0.147123  0.000469   
7   -4.024327  18.374921     0.093077     0.995659  0.147417  0.000708   
8   -4.023705  18.375038     0.093081     0.995658  0.147711  0.000948   
9   -4.023084  18.375155     0.093085     0.995658  0.148005  0.001187   

     ImuOrientX  ImuOrientY  ImuOrientZ  ImuOrientW  ...  ImuAccelYDelta64  \
Seq                                                  ...                     
0     -0.011154    0.006497   -0.101977   -0.994699  ...         -0.325611   
1     -0.010974    0.006144   -0.101975   -0.994703  ...         -0.550966   
2     -0.010794    0.005792   -0.101973   -0.994707  ...         -0.455497   
3     -0.010391    0.005561   -0.101971   -0.994713  ...         -0.360327   
4     -0.010383    0.007426   -0.101984   -0.994698  ...         -0.005387   
5     -0.010374    0.009292   -0.101997   -0.994683  ...          0.087388   
6     -0.010469    0.009854   -0.102001   -0.994676  ...          0.268749   
7     -0.010469    0.009854   -0.102001   -0.994676  ...          0.149638   
8     -0.010770    0.009128   -0.101993   -0.994681  ...          0.151433   
9     -0.011504    0.009034   -0.101988   -0.994674  ...          0.578798   

     ImuAccelZDelta2  ImuAccelZDelta4  ImuAccelZDelta8  ImuAccelZDelta16  \
Seq                                                                        
0           0.854132         1.829170         1.553837          0.088286   
1          -1.128866         1.206079        -0.420781         -1.149217   
2          -1.246181        -0.392050        -0.610222         -1.326387   
3          -0.936731        -2.065598        -0.490212         -1.177648   
4          -0.942418        -2.188600        -0.359429         -1.344045   
5          -1.257555        -2.194286        -0.988207         -1.860295   
6           0.702399        -0.240019        -0.632069         -0.529119   
7           1.331177         0.073622        -1.991976          1.043872   
8           0.648230         1.350629        -0.837971          0.715866   
9          -0.791883         0.539294        -1.654992         -2.075773   

     ImuAccelZDelta32  ImuAccelZDelta64  Speed  Terrain  Test  
Seq                                                            
0            0.581791          0.795174     15  MitTile     8  
1            1.366490          1.614889     15  MitTile     8  
2           -0.668281         -0.390254     15  MitTile     8  
3           -2.393602         -0.495001     15  MitTile     8  
4           -1.821090         -0.914885     15  MitTile     8  
5           -2.449867         -2.448071     15  MitTile     8  
6           -0.909198         -1.116895     15  MitTile     8  
7           -0.892438          0.396241     15  MitTile     8  
8            1.931522          1.717241     15  MitTile     8  
9           -0.154426         -1.140239     15  MitTile     8  

[10 rows x 121 columns]

In [4]:
print(df.isnull().sum().sum())
df.shape

0


(153052, 121)

In [5]:
# combined_labels = df['Speed'].map(str) + "_" + df['Terrain']
# combined_labels
for col in df.columns:
    print(col)

OdomPosX
OdomPosY
OdomOrientZ
OdomOrientW
OdomLinX
OdomAngZ
ImuOrientX
ImuOrientY
ImuOrientZ
ImuOrientW
ImuAngVelX
ImuAngVelY
ImuAngVelZ
ImuAccelX
ImuAccelY
ImuAccelZ
TimeDelta2
TimeDelta4
TimeDelta8
TimeDelta16
TimeDelta32
TimeDelta64
OdomPosXDelta2
OdomPosXDelta4
OdomPosXDelta8
OdomPosXDelta16
OdomPosXDelta32
OdomPosXDelta64
OdomPosYDelta2
OdomPosYDelta4
OdomPosYDelta8
OdomPosYDelta16
OdomPosYDelta32
OdomPosYDelta64
OdomOrientZDelta2
OdomOrientZDelta4
OdomOrientZDelta8
OdomOrientZDelta16
OdomOrientZDelta32
OdomOrientZDelta64
OdomOrientWDelta2
OdomOrientWDelta4
OdomOrientWDelta8
OdomOrientWDelta16
OdomOrientWDelta32
OdomOrientWDelta64
OdomLinXDelta2
OdomLinXDelta4
OdomLinXDelta8
OdomLinXDelta16
OdomLinXDelta32
OdomLinXDelta64
OdomAngZDelta2
OdomAngZDelta4
OdomAngZDelta8
OdomAngZDelta16
OdomAngZDelta32
OdomAngZDelta64
ImuOrientXDelta2
ImuOrientXDelta4
ImuOrientXDelta8
ImuOrientXDelta16
ImuOrientXDelta32
ImuOrientXDelta64
ImuOrientYDelta2
ImuOrientYDelta4
ImuOrientYDelta8
ImuOrientYDelt

In [6]:
le = preprocessing.LabelEncoder()

In [7]:
trainColumns = df[df['Test'] != 3]
testColumns = df[df['Test'] == 3]
trainColumns

OdomPosX   OdomPosY  OdomOrientZ  OdomOrientW  OdomLinX  OdomAngZ  \
Seq                                                                         
0      -4.032375  18.373403     0.093063     0.995660  0.152541  0.000100   
1      -4.031664  18.373537     0.093066     0.995660  0.153398  0.000885   
2      -4.029840  18.373881     0.093065     0.995660  0.151111  0.000587   
3      -4.028017  18.374225     0.093065     0.995660  0.148823  0.000288   
4      -4.026193  18.374569     0.093065     0.995660  0.146536 -0.000010   
...          ...        ...          ...          ...       ...       ...   
153047 -6.710423  13.805720     0.151013     0.988532  0.145356 -0.003765   
153048 -6.710423  13.805720     0.151013     0.988532  0.145356 -0.003765   
153049 -6.710423  13.805720     0.151013     0.988532  0.145356 -0.003765   
153050 -6.710423  13.805720     0.151013     0.988532  0.145356 -0.003765   
153051 -6.710423  13.805720     0.151013     0.988532  0.145356 -0.003765   

        ImuOrientX  ImuOrientY  ImuOrientZ  ImuOrientW  ...  ImuAccelYDelta64  \
Seq                                                     ...                     
0        -0.011154    0.006497   -0.101977   -0.994699  ...         -0.325611   
1        -0.010974    0.006144   -0.101975   -0.994703  ...         -0.550966   
2        -0.010794    0.005792   -0.101973   -0.994707  ...         -0.455497   
3        -0.010391    0.005561   -0.101971   -0.994713  ...         -0.360327   
4        -0.010383    0.007426   -0.101984   -0.994698  ...         -0.005387   
...            ...         ...         ...         ...  ...               ...   
153047   -0.013807    0.009487   -0.159757   -0.987010  ...         -0.058957   
153048   -0.013613    0.009750   -0.159733   -0.987014  ...         -0.350152   
153049   -0.012885    0.009198   -0.159698   -0.987034  ...         -0.726640   
153050   -0.012266    0.009053   -0.159704   -0.987043  ...         -0.665588   
153051   -0.012266    0.009053   -0.159704   -0.987043  ...         -0.665588   

        ImuAccelZDelta2  ImuAccelZDelta4  ImuAccelZDelta8  ImuAccelZDelta16  \
Seq                                                                           
0              0.854132         1.829170         1.553837          0.088286   
1             -1.128866         1.206079        -0.420781         -1.149217   
2             -1.246181        -0.392050        -0.610222         -1.326387   
3             -0.936731        -2.065598        -0.490212         -1.177648   
4             -0.942418        -2.188600        -0.359429         -1.344045   
...                 ...              ...              ...               ...   
153047        -0.462679        -1.469441        -2.051232         -0.265158   
153048        -0.718261        -1.828571        -1.830667         -2.195483   
153049         1.095946         0.633266         0.204105         -0.080804   
153050         1.284490         0.566229         0.805650          0.408212   
153051        -0.170587         0.925359        -0.544082          1.380857   

        ImuAccelZDelta32  ImuAccelZDelta64  Speed  Terrain  Test  
Seq                                                               
0               0.581791          0.795174     15  MitTile     8  
1               1.366490          1.614889     15  MitTile     8  
2              -0.668281         -0.390254     15  MitTile     8  
3              -2.393602         -0.495001     15  MitTile     8  
4              -1.821090         -0.914885     15  MitTile     8  
...                  ...               ...    ...      ...   ...  
153047         -0.201711         -1.783680     15  MitTile     6  
153048         -0.560842         -0.710480     15  MitTile     6  
153049          0.979229          1.491588     15  MitTile     6  
153050          0.808642          0.643442     15  MitTile     6  
153051          1.220445          0.643442     15  MitTile     6  

[133132 rows x 121 columns]

In [8]:
X_train = trainColumns.drop(columns=['Speed', 'Terrain'])
columnsToDrop = [x for x in X_train.columns.tolist() if 'Time' in x or 'Delta' not in x or 'Orient' in x or 'Pos' in x]
X_train = X_train.drop(columns=columnsToDrop)
y_train = le.fit_transform(trainColumns['Terrain'])

X_test = testColumns.drop(columns=['Speed', 'Terrain'])
columnsToDrop = [x for x in X_test.columns.tolist() if 'Time' in x or 'Delta' not in x or 'Orient' in x or 'Pos' in x]
X_test = X_test.drop(columns=columnsToDrop)
y_test = le.fit_transform(testColumns['Terrain'])

In [9]:
# X.columns

In [12]:
scaler = StandardScaler()

scaledFeatures = scaler.fit_transform(X_train.values)

X_train = pd.DataFrame(scaledFeatures, columns = X_train.columns.tolist())

scaledFeatures = scaler.fit_transform(X_test.values)

X_test = pd.DataFrame(scaledFeatures, columns =X_test.columns.tolist())

In [13]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [14]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [15]:
y_pred = model.predict(X_test)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[2398 1985 1720   59]
 [ 335  799   46 1296]
 [3188 1273  705   78]
 [  64  141    6 5827]]
              precision    recall  f1-score   support

           0       0.40      0.39      0.39      6162
           1       0.19      0.32      0.24      2476
           2       0.28      0.13      0.18      5244
           3       0.80      0.97      0.88      6038

    accuracy                           0.49     19920
   macro avg       0.42      0.45      0.42     19920
weighted avg       0.47      0.49      0.47     19920



In [ ]:
# from sklearn import metrics
# print("Accuracy:",metrics.accuracy_score(y_test, y_pred))