In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [2]:
folder = "~/Desktop/Design Teams/QMIND"
file = "AllData_4T.csv"

df = pd.read_csv(os.path.join(folder, file))

In [3]:
df = df.rename(columns={'Unnamed: 0': 'Seq'})
df = df.drop(columns=['Unnamed: 0.1'])
df = df.set_index('Seq')
df.head(10)

ImuAccelX  ImuAccelXDelta16  ImuAccelXDelta2  ImuAccelXDelta32  \
Seq                                                                   
0     0.512958          0.429161        -0.110133          0.224756   
1     0.512958          0.312443        -0.030526         -0.026336   
2     0.299874          0.063446        -0.213084         -0.208894   
3     0.396540          0.160112        -0.116418          0.550367   
4     0.493206          0.422876         0.193332          0.647033   
5     0.493206          0.588974         0.096666          0.767940   
6     0.153827         -0.472855        -0.339378          0.238223   
7     0.461482          0.183755        -0.031723          0.355539   
8    -0.330998         -0.259771        -0.484826         -0.436942   
9    -0.330998         -0.748787        -0.792481         -0.694917   

     ImuAccelXDelta4  ImuAccelXDelta64  ImuAccelXDelta8  ImuAccelY  \
Seq                                                                  
0           0.831985          0.084396         0.584185   0.362123   
1           0.360926          0.084396         0.095170   0.362123   
2          -0.323217         -0.256778        -0.117914   0.486023   
3          -0.146944          0.360028         0.320524   0.338480   
4          -0.019752          0.413598         0.812233   0.190938   
5          -0.019752          0.386065         0.341174   0.190938   
6          -0.146046          0.019154        -0.469264   0.046687   
7           0.064943          0.297480        -0.082001   0.308852   
8          -0.824204         -0.566528        -0.843956   0.581192   
9          -0.824204         -0.638055        -0.843956   0.581192   

     ImuAccelYDelta16  ImuAccelYDelta2  ...  OdomPosYDelta64  OdomPosYDelta8  \
Seq                                     ...                                    
0            0.256778         0.401029  ...        -0.008034       -0.000935   
1            0.286107         0.041300  ...        -0.008030       -0.000936   
2            0.002993         0.123900  ...        -0.008026       -0.000937   
3           -0.144550        -0.023643  ...        -0.008022       -0.000938   
4           -0.301071        -0.295085  ...        -0.008001       -0.000922   
5           -0.310049        -0.147543  ...        -0.007981       -0.000907   
6           -0.017358        -0.144251  ...        -0.007855       -0.000891   
7            0.191237         0.117914  ...        -0.007729       -0.000875   
8            0.410007         0.534506  ...        -0.007603       -0.000859   
9            0.426766         0.272340  ...        -0.007616       -0.000843   

     Speed  Terrain  TimeDelta16  TimeDelta2  TimeDelta32  TimeDelta4  \
Seq                                                                     
0       10  MitTile     0.093692    0.008937     0.186218    0.025357   
1       10  MitTile     0.093896    0.009665     0.182783    0.020521   
2       10  MitTile     0.093565    0.009493     0.182142    0.018430   
3       10  MitTile     0.098352    0.013971     0.186415    0.023636   
4       10  MitTile     0.098007    0.016409     0.187719    0.025902   
5       10  MitTile     0.094178    0.011486     0.188191    0.025457   
6       10  MitTile     0.094940    0.009745     0.186901    0.026153   
7       10  MitTile     0.090898    0.010667     0.184012    0.022153   
8       10  MitTile     0.088632    0.009933     0.184024    0.019678   
9       10  MitTile     0.088634    0.008729     0.184147    0.019396   

     TimeDelta64  TimeDelta8  
Seq                           
0       0.374362    0.043052  
1       0.375165    0.043781  
2       0.375130    0.043885  
3       0.380157    0.048728  
4       0.379358    0.051259  
5       0.376585    0.045978  
6       0.374921    0.044583  
7       0.375836    0.045790  
8       0.369838    0.045579  
9       0.365866    0.044854  

[10 rows x 120 columns]

In [4]:
print(df.isnull().sum().sum())
df.shape

0


(378905, 120)

In [5]:
# combined_labels = df['Speed'].map(str) + "_" + df['Terrain']
# combined_labels
for col in df.columns:
    print(col)

ImuAccelX
ImuAccelXDelta16
ImuAccelXDelta2
ImuAccelXDelta32
ImuAccelXDelta4
ImuAccelXDelta64
ImuAccelXDelta8
ImuAccelY
ImuAccelYDelta16
ImuAccelYDelta2
ImuAccelYDelta32
ImuAccelYDelta4
ImuAccelYDelta64
ImuAccelYDelta8
ImuAccelZ
ImuAccelZDelta16
ImuAccelZDelta2
ImuAccelZDelta32
ImuAccelZDelta4
ImuAccelZDelta64
ImuAccelZDelta8
ImuAngVelX
ImuAngVelXDelta16
ImuAngVelXDelta2
ImuAngVelXDelta32
ImuAngVelXDelta4
ImuAngVelXDelta64
ImuAngVelXDelta8
ImuAngVelY
ImuAngVelYDelta16
ImuAngVelYDelta2
ImuAngVelYDelta32
ImuAngVelYDelta4
ImuAngVelYDelta64
ImuAngVelYDelta8
ImuAngVelZ
ImuAngVelZDelta16
ImuAngVelZDelta2
ImuAngVelZDelta32
ImuAngVelZDelta4
ImuAngVelZDelta64
ImuAngVelZDelta8
ImuOrientW
ImuOrientWDelta16
ImuOrientWDelta2
ImuOrientWDelta32
ImuOrientWDelta4
ImuOrientWDelta64
ImuOrientWDelta8
ImuOrientX
ImuOrientXDelta16
ImuOrientXDelta2
ImuOrientXDelta32
ImuOrientXDelta4
ImuOrientXDelta64
ImuOrientXDelta8
ImuOrientY
ImuOrientYDelta16
ImuOrientYDelta2
ImuOrientYDelta32
ImuOrientYDelta4
ImuOrientYDe

In [6]:
le = preprocessing.LabelEncoder()

In [7]:
X = df.drop(columns=['Speed', 'Terrain'])
# columnsToKeep = [col for col in df.columns.tolist() if 'Delta' in col and 'Accel' in col]
# X = df[columnsToKeep]
# columnsToDrop = [col for col in X.columns.tolist() if 'Time' in col or 'Odom' in col]
columnsToDrop = [x for x in X.columns.tolist() if 'Time' in x or 'Delta' not in x or 'Orient' in x or 'Pos' in x]
X = X.drop(columns=columnsToDrop)
# y = le.fit_transform(combined_labels)
y = le.fit_transform(df['Terrain'])

In [8]:
X.columns

Index(['ImuAccelXDelta16', 'ImuAccelXDelta2', 'ImuAccelXDelta32',
       'ImuAccelXDelta4', 'ImuAccelXDelta64', 'ImuAccelXDelta8',
       'ImuAccelYDelta16', 'ImuAccelYDelta2', 'ImuAccelYDelta32',
       'ImuAccelYDelta4', 'ImuAccelYDelta64', 'ImuAccelYDelta8',
       'ImuAccelZDelta16', 'ImuAccelZDelta2', 'ImuAccelZDelta32',
       'ImuAccelZDelta4', 'ImuAccelZDelta64', 'ImuAccelZDelta8',
       'ImuAngVelXDelta16', 'ImuAngVelXDelta2', 'ImuAngVelXDelta32',
       'ImuAngVelXDelta4', 'ImuAngVelXDelta64', 'ImuAngVelXDelta8',
       'ImuAngVelYDelta16', 'ImuAngVelYDelta2', 'ImuAngVelYDelta32',
       'ImuAngVelYDelta4', 'ImuAngVelYDelta64', 'ImuAngVelYDelta8',
       'ImuAngVelZDelta16', 'ImuAngVelZDelta2', 'ImuAngVelZDelta32',
       'ImuAngVelZDelta4', 'ImuAngVelZDelta64', 'ImuAngVelZDelta8',
       'OdomAngZDelta16', 'OdomAngZDelta2', 'OdomAngZDelta32',
       'OdomAngZDelta4', 'OdomAngZDelta64', 'OdomAngZDelta8',
       'OdomLinXDelta16', 'OdomLinXDelta2', 'OdomLinXDelta32',
       '

In [9]:
scaler = StandardScaler()

scaledFeatures = scaler.fit_transform(X.values)

X = pd.DataFrame(scaledFeatures, columns = X.columns.tolist())

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [11]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [12]:
y_pred = model.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10197    26   157    18]
 [  351  9278   736  1666]
 [ 2112   303 23256   175]
 [   20   118    32 27336]]
              precision    recall  f1-score   support

           0       0.80      0.98      0.88     10398
           1       0.95      0.77      0.85     12031
           2       0.96      0.90      0.93     25846
           3       0.94      0.99      0.96     27506

    accuracy                           0.92     75781
   macro avg       0.91      0.91      0.91     75781
weighted avg       0.93      0.92      0.92     75781



In [14]:
# from sklearn import metrics
# print("Accuracy:",metrics.accuracy_score(y_test, y_pred))